"options":
  "i40e-lldp-stop":
    "type": "boolean"
    "default": !!bool "True"
    "description": |
       "This allows control over Intel's i40e NIC driver. By default
       i40e blocks userspace LLDP and does it on its own. Setting this
       option to 'True' means charm will disable this functionality in
       the NIC and do it within userspace."
  "interfaces-regex":
    "type": "string"
    "default": ""
    "description": |
       "Which interfaces should lldpd announce details. If you want lldpd
       to listen on multiple interfaces, set it here. Examples:

       seth*,meth*

       You can also use exclamation mark to exclude an interface:

       eth*,!eth1

       This way lldpd will listen on all eth* interfaces with an
       exception of eth1.

       By default this is set to None, which puts lldpd in listening
       mode only."
  "systemid-from-interface":
    "type": "string"
    "default": ""
    "description": "Pull systemID from this interface"
  "enable-snmp":
    "type": "boolean"
    "default": False
    "description": "Enable the SNMP agent for LLDPD"
  "short-name":
    "type": "boolean"
    "default": !!bool "False"
    "description": "Set short name in SysName instead of FQDN"
  nagios_context:
    default: "juju"
    type: string
    description: |
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: "juju"
    type: string
    description: |
      Comma separated list of nagios servicegroups for the check
